spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true

#springdatasource.url = jdbc:mysql://localhost:3306/blog
#  # ?useSSL=false&serverTimezone=UTC
#spring.datasource.username = root
#spring.datasource.password = root
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
